zuul:
  ribbon:
    eager-load:
      enabled: true
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
    connect-timeout-millis: 3000
    socket-timeout-millis: 120000
  routes:
    rbacs:
      path: /rbacs/**
      serviceId: rbac-service

ribbon:
  ReadTimeout: 600000

jwt: 
  # header:凭证(校验的变量名)
  header: X-AUTH
  # 有效期(单位:s), 0为不检查
  expire: 0
  # 秘钥(普通字符串)
  secret: cb1b43f7e6407abe23067411c1c9b7b3

permiturl:
  permitAll:
    - /rbacs/resources/auth
    - /rbacs/members/service/login
    - /rbacs/members/login