permiturl:
  permitAll:
    - /favicon.ico
    - /web/**
  devSwaggerUrl:
    - /swagger-ui.html
    - /swagger-resources/configuration/ui
    - /webjars/springfox-swagger-ui/**
    - /swagger-resources/configuration/security
    - /swagger-resources
    - /v2/api-docs
    - /csrf
swagger:
  v2ApiDocs:
    mapping: /v2/api-docs

jwt: 
  # header:凭证(校验的变量名)
  header: X-AUTH
  # 有效期(单位:s), 0为不检查
  expire: 0
  # 秘钥(普通字符串)
  secret: cb1b43f7e6407abe23067411c1c9b7b3
  
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 1
      pool-name: dbcp1
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://141.3.119.54:9918/rbacs?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Bmsoft2018
    type: com.zaxxer.hikari.HikariDataSource


ribbon:
  ReadTimeout: 10000

