permiturl:
  permitAll:
    - /favicon.ico
    - /web/**
  devSwaggerUrl:
    - /swagger-ui.html
    - /swagger-resources/configuration/ui
    - /webjars/springfox-swagger-ui/**
    - /swagger-resources/configuration/security
    - /swagger-resources
    - /v2/api-docs
    - /csrf
swagger:
  v2ApiDocs:
    mapping: /v2/api-docs

jwt: 
  # header:凭证(校验的变量名)
  header: X-AUTH
  # 有效期(单位:s), 0为不检查
  expire: 0
  # 秘钥(普通字符串)
  secret: cb1b43f7e6407abe23067411c1c9b7b3
  
spring:
  datasource:
    rbac:
      jdbc-url: jdbc:mysql://141.112.1.9:9918/rbac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: Bmsoft12#$
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        minimum-idle: 1
        maximum-pool-size: 1
        connection-test-query: SELECT 1
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000
        type: com.zaxxer.hikari.HikariDataSource
    
    member:
      jdbc-url: jdbc:mysql://141.112.1.9:9918/tyyh?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: Bmsoft12#$
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        minimum-idle: 1
        maximum-pool-size: 1
        connection-test-query: SELECT 1
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000
        type: com.zaxxer.hikari.HikariDataSource


ribbon:
  ReadTimeout: 10000

